[package]
name = "simple-handout-template"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["chillcicada"]
license = "MIT"
description = "A simple handout template."
repository = "https://github.com/chillcicada/simple-handout-template"
keywords = ["book", "handout", "template"]
# categories = ["template"]
exclude = [".*", "example"]
compiler = "0.13.0"

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"
